-- CREATE
CREATE TABLE MEMBER (
    MEM_CODE			NUMBER,
    MEM_NAME			VARCHAR2(2000),
    MEM_EMAIL			VARCHAR2(2000),
    MEM_PASSWORD		VARCHAR2(2000),
    MEM_GENDER			VARCHAR2(100),
    MEM_TYPE			VARCHAR2(100),
    MEM_IS_DELETED		NUMBER
);

CREATE TABLE NOTICE (
    NOT_CODE			NUMBER,
    NOT_TYPE			VARCHAR2(100),
    NOT_TITLE			VARCHAR2(2000),
    NOT_CONTENT			CLOB,
    NOT_DATE			DATE
);

CREATE TABLE PASSAGE (
    PAS_CODE			NUMBER,
    PAS_TITLE			VARCHAR2(2000),
    PAS_CONTENT		    CLOB,
    PAS_GIST			VARCHAR2(2000),
    PAS_DATE			DATE,
    PAS_IS_FAVORITE	    NUMBER,
    PAS_IS_DELETED		NUMBER,
    PAS_IS_GENERATED    NUMBER,
    MEM_CODE			NUMBER,
    SUB_CODE			NUMBER
);

CREATE TABLE PAYMENT (
    PAY_CODE			NUMBER,
    PAY_PRICE			NUMBER,
    PAY_DATE			DATE,
    MEM_CODE			NUMBER,
    TIC_CODE			NUMBER
);

CREATE TABLE QUESTION (
    QUE_CODE			NUMBER,
    QUE_QUERY			CLOB,
    QUE_OPTION		    CLOB,
    QUE_ANSWER		    CLOB,
    PAS_CODE			NUMBER
);

CREATE TABLE SUBJECT (
    SUB_CODE			NUMBER,
    SUB_TYPE			VARCHAR2(100),
    SUB_KEYWORD		    VARCHAR2(2000)
);

CREATE TABLE TICKET (
    TIC_CODE			NUMBER,
    TIC_NUMBER			NUMBER,
    TIC_PRICE			NUMBER
);

CREATE TABLE USAGE (
    USA_CODE			NUMBER,
    USA_TYPE			VARCHAR2(100),
    USA_DATE			DATE,
    USA_COUNT			NUMBER,
    USA_BALANCE			NUMBER,
    MEM_CODE			NUMBER
);

---------------------------------------------------

-- PK
ALTER TABLE MEMBER		ADD CONSTRAINT PK_MEMBER			PRIMARY KEY (MEM_CODE);
ALTER TABLE NOTICE		ADD CONSTRAINT PK_NOTICE			PRIMARY KEY (NOT_CODE);
ALTER TABLE PASSAGE		ADD CONSTRAINT PK_PASSAGE			PRIMARY KEY (PAS_CODE);
ALTER TABLE PAYMENT		ADD CONSTRAINT PK_PAYMENT			PRIMARY KEY (PAY_CODE);
ALTER TABLE QUESTION	ADD CONSTRAINT PK_QUESTION			PRIMARY KEY (QUE_CODE);
ALTER TABLE SUBJECT		ADD CONSTRAINT PK_SUBJECT			PRIMARY KEY (SUB_CODE);
ALTER TABLE TICKET		ADD CONSTRAINT PK_TICKET			PRIMARY KEY (TIC_CODE);
ALTER TABLE USAGE		ADD CONSTRAINT PK_USAGE				PRIMARY KEY (USA_CODE);

---------------------------------------------------

-- DEFAULT
ALTER TABLE MEMBER
    MODIFY MEM_IS_DELETED DEFAULT 0;

ALTER TABLE PASSAGE
    MODIFY PAS_IS_FAVORITE DEFAULT 0;

ALTER TABLE PASSAGE
    MODIFY PAS_IS_DELETED DEFAULT 0;

ALTER TABLE PASSAGE
    MODIFY PAS_IS_GENERATED DEFAULT 0;

ALTER TABLE USAGE
    MODIFY USA_BALANCE DEFAULT 5;

---------------------------------------------------

-- SEQUENCE
CREATE SEQUENCE SEQ_MEM_NO NOCACHE;
CREATE SEQUENCE SEQ_NOT_NO NOCACHE;
CREATE SEQUENCE SEQ_PAS_NO NOCACHE;
CREATE SEQUENCE SEQ_PAY_NO NOCACHE;
CREATE SEQUENCE SEQ_QUE_NO NOCACHE;
CREATE SEQUENCE SEQ_SUB_NO NOCACHE;
CREATE SEQUENCE SEQ_TIC_NO NOCACHE;
CREATE SEQUENCE SEQ_USA_NO NOCACHE;