-- CREATE
CREATE TABLE MEMBER (
    MEM_CODE			NUMBER,
    MEM_EMAIL			VARCHAR2(2000),
    MEM_GENDER			VARCHAR2(100),
    MEM_IS_DELETED		NUMBER,
    MEM_NAME			VARCHAR2(2000),
    MEM_PASSWORD		VARCHAR2(2000),
    MEM_TYPE			VARCHAR2(100)
);

CREATE TABLE NOTICE (
    NOT_CODE			NUMBER,
    NOT_CONTENT			CLOB,
    NOT_DATE			DATE,
    NOT_TITLE			VARCHAR2(2000),
    NOT_TYPE			VARCHAR2(100)
);

CREATE TABLE PASSAGE (
     MEM_CODE			NUMBER,
     PAS_CODE			NUMBER,
     PAS_CONTENT		CLOB,
     PAS_DATE			DATE,
     PAS_GIST			VARCHAR2(2000),
     PAS_IS_DELETED		NUMBER,
     PAS_IS_FAVORITE	NUMBER,
     PAS_TITLE			VARCHAR2(2000),
     SUB_CODE			NUMBER
);

CREATE TABLE PAYMENT (
     MEM_CODE			NUMBER,
     PAY_CODE			NUMBER,
     PAY_DATE			DATE,
     PAY_PRICE			NUMBER,
     TIC_CODE			NUMBER
);

CREATE TABLE QUESTION (
      PAS_CODE			NUMBER,
      QUE_ANSWER		CLOB,
      QUE_CODE			NUMBER,
      QUE_OPTION		CLOB,
      QUE_QUERY			CLOB
);

CREATE TABLE SUBJECT (
     SUB_CODE			NUMBER,
     SUB_KEYWORD		VARCHAR2(2000),
     SUB_TYPE			VARCHAR2(100)
);

CREATE TABLE TICKET (
    TIC_CODE			NUMBER,
    TIC_NUMBER			NUMBER,
    TIC_PRICE			NUMBER
);

CREATE TABLE USAGE (
    MEM_CODE			NUMBER,
    USA_BALANCE			NUMBER,
    USA_CODE			NUMBER,
    USA_COUNT			NUMBER,
    USA_DATE			DATE,
    USA_TYPE			VARCHAR2(100)
);

---------------------------------------------------

-- PK
ALTER TABLE MEMBER		ADD CONSTRAINT PK_MEMBER			PRIMARY KEY (MEM_CODE);
ALTER TABLE NOTICE		ADD CONSTRAINT PK_NOTICE			PRIMARY KEY (NOT_CODE);
ALTER TABLE PASSAGE		ADD CONSTRAINT PK_PASSAGE			PRIMARY KEY (PAS_CODE);
ALTER TABLE PAYMENT		ADD CONSTRAINT PK_PAYMENT			PRIMARY KEY (PAY_CODE);
ALTER TABLE QUESTION	ADD CONSTRAINT PK_QUESTION			PRIMARY KEY (QUE_CODE);
ALTER TABLE SUBJECT		ADD CONSTRAINT PK_SUBJECT			PRIMARY KEY (SUB_CODE);
ALTER TABLE TICKET		ADD CONSTRAINT PK_TICKET			PRIMARY KEY (TIC_CODE);
ALTER TABLE USAGE		ADD CONSTRAINT PK_USAGE				PRIMARY KEY (USA_CODE);

---------------------------------------------------

-- DEFAULT
ALTER TABLE MEMBER
    MODIFY MEM_IS_DELETED DEFAULT 0;

ALTER TABLE PASSAGE
    MODIFY PAS_IS_DELETED DEFAULT 0;

ALTER TABLE PASSAGE
    MODIFY PAS_IS_FAVORITE DEFAULT 0;

ALTER TABLE USAGE
    MODIFY USA_BALANCE DEFAULT 5;

---------------------------------------------------

-- SEQUENCE
CREATE SEQUENCE SEQ_MEM_NO NOCACHE;
CREATE SEQUENCE SEQ_NOT_NO NOCACHE;
CREATE SEQUENCE SEQ_PAS_NO NOCACHE;
CREATE SEQUENCE SEQ_PAY_NO NOCACHE;
CREATE SEQUENCE SEQ_QUE_NO NOCACHE;
CREATE SEQUENCE SEQ_SUB_NO NOCACHE;
CREATE SEQUENCE SEQ_TIC_NO NOCACHE;
CREATE SEQUENCE SEQ_USA_NO NOCACHE;
