-- TABLE
DROP TABLE MEMBER;
DROP TABLE NOTICE;
DROP TABLE PASSAGE;
DROP TABLE PAYMENT;
DROP TABLE QUESTION;
DROP TABLE SUBJECT;
DROP TABLE TICKET;
DROP TABLE USAGE;

---------------------------------------------------

-- SEQUENCE
DROP SEQUENCE SEQ_MEM_NO;
DROP SEQUENCE SEQ_NOT_NO;
DROP SEQUENCE SEQ_PAS_NO;
DROP SEQUENCE SEQ_PAY_NO;
DROP SEQUENCE SEQ_QUE_NO;
DROP SEQUENCE SEQ_SUB_NO;
DROP SEQUENCE SEQ_TIC_NO;
DROP SEQUENCE SEQ_USA_NO;