-- 시퀀스 삭제
DROP SEQUENCE SEQ_MEM_NO;
DROP SEQUENCE SEQ_TIC_NO;
DROP SEQUENCE SEQ_PAY_NO;
DROP SEQUENCE SEQ_SUB_NO;
DROP SEQUENCE SEQ_PAS_NO;
DROP SEQUENCE SEQ_QUE_NO;
DROP SEQUENCE SEQ_NOT_NO;
DROP SEQUENCE SEQ_USA_NO;
-- 시퀀스 추가
CREATE SEQUENCE SEQ_MEM_NO    NOCACHE;
CREATE SEQUENCE SEQ_TIC_NO    NOCACHE;
CREATE SEQUENCE SEQ_PAY_NO    NOCACHE;
CREATE SEQUENCE SEQ_SUB_NO    NOCACHE;
CREATE SEQUENCE SEQ_PAS_NO    NOCACHE;
CREATE SEQUENCE SEQ_QUE_NO    NOCACHE;
CREATE SEQUENCE SEQ_NOT_NO    NOCACHE;
CREATE SEQUENCE SEQ_USA_NO    NOCACHE;

-- 테이블 삭제 ( FK 제약 조건 연결시 삭제 순서 고려해야함. 알파벳 순 x )
DROP TABLE TEST_MEMBER;
DROP TABLE USAGE;
DROP TABLE QUESTION;
DROP TABLE PASSAGE;
DROP TABLE SUBJECT;
DROP TABLE PAYMENT;
DROP TABLE MEMBER;
DROP TABLE TICKET;
DROP TABLE NOTICE;
-- 사용자의 모든 휴지통 항목 비우기
PURGE RECYCLEBIN;
SELECT * FROM TAB;

-- 테이블 추가 ( PK, FK 제약조건 추가하고 싶지 않을 경우 아래 ALTER 실행하지 않기 )
CREATE TABLE TEST_MEMBER (
    MEMBER_CODE	NUMBER              NOT NULL,
    NAME VARCHAR2(255)              NULL,
    AGE	NUMBER                      NULL,
    BIRTHDAY DATE                   NULL
);

CREATE TABLE USAGE (
    USA_CODE	NUMBER              NOT NULL,
    USA_TYPE	VARCHAR2(200)       NOT NULL CHECK (USA_TYPE IN ('회원가입', '지문 생성', '문항 생성', '오픈 이벤트', '이용권 충전')),
    USA_COUNT	NUMBER              NULL,
    USA_REMAIN	NUMBER              NULL,
    USA_DATE	DATE                NULL,
    -- 가상 외래키
    MEM_CODE	NUMBER              NOT NULL
);

CREATE TABLE MEMBER (
    MEM_CODE NUMBER                 NOT NULL ,
    MEM_NAME VARCHAR2(2000)         NOT NULL,
    MEM_EMAIL VARCHAR2(2000)        NOT NULL UNIQUE,
    MEM_PASSWORD VARCHAR2(2000)     NOT NULL,
    MEM_GENDER VARCHAR2(10)         CHECK (MEM_GENDER IN ('남성', '여성')),
    MEM_TYPE VARCHAR2(20)           CHECK (MEM_TYPE IN ('초등교사', '중등교사', '고등교사', '학원', '기업', '학부모', '학생', '기타')),
    MEM_TICKET NUMBER               DEFAULT 5 NOT NULL,
    MEM_IS_DELETED NUMBER           DEFAULT 0
    -- 가상 외래키
);

CREATE TABLE QUESTION (
    QUE_CODE	NUMBER		        NOT NULL,
    QUE_QUESTION	CLOB		    NULL,
    QUE_OPTIONS	CLOB		        NULL,
    QUE_ANSWER	CLOB		        NULL,
    QUE_PATTERN	VARCHAR2(10)		NULL CHECK (QUE_PATTERN IN ('전체', '사실적 읽기', '추론적 읽기', '비판적 읽기', '어휘 및 문법')),
    QUE_TYPE	VARCHAR2(10)		NULL CHECK (QUE_TYPE IN ('전체', '정답형', '부정형')),
    QUE_LEVEL	VARCHAR2(10)		NULL CHECK (QUE_LEVEL IN ('상', '중', '하')),
    QUE_CREATED_AT DATE             NULL,
    QUE_MODIFIED_AT DATE            NULL,
    QUE_IS_DELETED NUMBER           DEFAULT 0,
    -- 가상 외래키
    PAS_CODE    NUMBER              NOT NULL
);

CREATE TABLE PASSAGE (
    PAS_CODE	NUMBER		        NOT NULL,
    PAS_TITLE	VARCHAR2(2000)		NULL,
    PAS_CONTENT	CLOB		        NULL,
    PAS_GIST	VARCHAR2(2000)		NULL,
    PAS_FAVORITE	NUMBER	        DEFAULT 0 NOT NULL CHECK (PAS_FAVORITE IN (0, 1)),
    PAS_CREATED_AT DATE             NULL,
    PAS_MODIFIED_AT DATE            NULL,
    PAS_IS_DELETED NUMBER           DEFAULT 0,
    -- 가상 외래키
    SUB_CODE	NUMBER		        NOT NULL,
    MEM_CODE	NUMBER		        NOT NULL
);

CREATE TABLE SUBJECT (
     SUB_CODE	NUMBER		        NOT NULL,
     SUB_TYPE	VARCHAR2(10)		NOT NULL CHECK (SUB_TYPE IN ('인문', '예술', '사회', '문화', '과학', '기술')),
     SUB_KEYWORD	VARCHAR2(2000)	    NULL
);

CREATE TABLE PAYMENT (
    PAY_CODE	NUMBER		        NOT NULL,
    PAY_PRICE	NUMBER		        NULL,
    PAY_DATE	DATE		        NULL,
    -- 가상 외래키
    MEM_CODE	NUMBER		        NOT NULL,
    TIC_CODE	NUMBER	            NOT NULL
);

CREATE TABLE NOTICE (
    NOT_CODE	NUMBER		        NOT NULL,
    NOT_TYPE	VARCHAR2(10)		NULL CHECK (NOT_TYPE IN ('서비스', '작업')),
    NOT_TITLE	VARCHAR2(2000)		NULL,
    NOT_CONTENT	CLOB		        NULL,
    NOT_DATE	DATE		        NULL
);

CREATE TABLE TICKET (
    TIC_CODE	NUMBER		        NOT NULL,
    TIC_NUMBER	NUMBER              NOT NULL CHECK (TIC_NUMBER IN (10, 50, 100)),
    TIC_PRICE	NUMBER              NOT NULL CHECK (TIC_PRICE IN (10000, 40000, 70000))
);

-- PK 제약 조건 추가
ALTER TABLE USAGE ADD CONSTRAINT PK_USAGE PRIMARY KEY (USA_CODE);
ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEM_CODE);
ALTER TABLE SUBJECT ADD CONSTRAINT PK_SUBJECT PRIMARY KEY (SUB_CODE);
ALTER TABLE QUESTION ADD CONSTRAINT PK_QUESTION PRIMARY KEY (QUE_CODE);
ALTER TABLE PASSAGE ADD CONSTRAINT PK_PASSAGE PRIMARY KEY (PAS_CODE);
ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (PAY_CODE);
ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOT_CODE);
ALTER TABLE TICKET ADD CONSTRAINT PK_TICKET PRIMARY KEY (TIC_CODE);

-- FK 제약 조건 추가 ( Non Identifying Relationship Constraint )
ALTER TABLE USAGE ADD CONSTRAINT FK_MEMBER_TO_USAGE_1 FOREIGN KEY (MEM_CODE)
    REFERENCES MEMBER (MEM_CODE);
ALTER TABLE QUESTION ADD CONSTRAINT FK_PASSAGE_TO_QUESTION_1 FOREIGN KEY (PAS_CODE)
    REFERENCES PASSAGE (PAS_CODE);
ALTER TABLE PASSAGE ADD CONSTRAINT FK_SUBJECT_TO_PASSAGE_1 FOREIGN KEY (SUB_CODE)
    REFERENCES SUBJECT (SUB_CODE);
ALTER TABLE PASSAGE ADD CONSTRAINT FK_MEMBER_TO_PASSAGE_1 FOREIGN KEY (MEM_CODE)
    REFERENCES MEMBER (MEM_CODE);
ALTER TABLE PAYMENT ADD CONSTRAINT FK_MEMBER_TO_PAYMENT_1 FOREIGN KEY (MEM_CODE)
    REFERENCES MEMBER (MEM_CODE);
ALTER TABLE PAYMENT ADD CONSTRAINT FK_TICKET_TO_PAYMENT_1 FOREIGN KEY (TIC_CODE)
    REFERENCES TICKET (TIC_CODE);

SELECT * FROM TAB;