--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "GENIEQ"."MEMBER" 
   (	"MEM_CODE" NUMBER, 
	"MEM_NAME" VARCHAR2(255 CHAR), 
	"MEM_EMAIL" VARCHAR2(255 CHAR), 
	"MEM_PASSWORD" VARCHAR2(255 CHAR), 
	"MEM_GENDER" VARCHAR2(255 CHAR), 
	"MEM_TYPE" VARCHAR2(255 CHAR), 
	"MEM_IS_DELETED" NUMBER DEFAULT 0, 
	 CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
