--------------------------------------------------------
--  Ref Constraints for Table PASSAGE
--------------------------------------------------------

  ALTER TABLE "GENIEQ"."PASSAGE" ADD CONSTRAINT "FK6XNK24G6N3SW7OU8WBDTHN8ND" FOREIGN KEY ("MEM_CODE")
	  REFERENCES "GENIEQ"."MEMBER" ("MEM_CODE") ENABLE
  ALTER TABLE "GENIEQ"."PASSAGE" ADD CONSTRAINT "FKQYMPUQDKMRWYSOVF9BKX1IOOC" FOREIGN KEY ("SUB_CODE")
	  REFERENCES "GENIEQ"."SUBJECT" ("SUB_CODE") ENABLE
