--------------------------------------------------------
--  DDL for Table PASSAGE
--------------------------------------------------------

  CREATE TABLE "GENIEQ"."PASSAGE" 
   (	"PAS_CODE" NUMBER, 
	"PAS_TYPE" VARCHAR2(255 CHAR), 
	"PAS_KEYWORD" VARCHAR2(255 CHAR), 
	"PAS_TITLE" VARCHAR2(255 CHAR), 
	"PAS_CONTENT" CLOB, 
	"PAS_DATE" DATE DEFAULT SYSDATE, 
	"PAS_IS_FAVORITE" NUMBER DEFAULT 0, 
	"PAS_IS_DELETED" NUMBER DEFAULT 0, 
	"PAS_IS_GENERATED" NUMBER DEFAULT 0, 
	"MEM_CODE" NUMBER, 
	"SUB_CODE" NUMBER(19,0), 
	"PAS_GIST" CLOB, 
	 CONSTRAINT "PK_PASSAGE" PRIMARY KEY ("PAS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKQYMPUQDKMRWYSOVF9BKX1IOOC" FOREIGN KEY ("SUB_CODE")
	  REFERENCES "GENIEQ"."SUBJECT" ("SUB_CODE") ENABLE, 
	 CONSTRAINT "FK6XNK24G6N3SW7OU8WBDTHN8ND" FOREIGN KEY ("MEM_CODE")
	  REFERENCES "GENIEQ"."MEMBER" ("MEM_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PAS_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PAS_GIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
