--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "GENIEQ"."PAYMENT" ADD CONSTRAINT "FK7HRN7PDAS07VDHE7YSVSPOR25" FOREIGN KEY ("MEM_CODE")
	  REFERENCES "GENIEQ"."MEMBER" ("MEM_CODE") ENABLE
  ALTER TABLE "GENIEQ"."PAYMENT" ADD CONSTRAINT "FKFFNW8E7F56UGCAYQEUB2FNHWF" FOREIGN KEY ("TIC_CODE")
	  REFERENCES "GENIEQ"."TICKET" ("TIC_CODE") ENABLE
