--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "GENIEQ"."PAYMENT" 
   (	"PAY_CODE" NUMBER, 
	"PAY_PRICE" NUMBER, 
	"PAY_DATE" DATE, 
	"MEM_CODE" NUMBER, 
	"TIC_CODE" NUMBER, 
	 CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PAY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK7HRN7PDAS07VDHE7YSVSPOR25" FOREIGN KEY ("MEM_CODE")
	  REFERENCES "GENIEQ"."MEMBER" ("MEM_CODE") ENABLE, 
	 CONSTRAINT "FKFFNW8E7F56UGCAYQEUB2FNHWF" FOREIGN KEY ("TIC_CODE")
	  REFERENCES "GENIEQ"."TICKET" ("TIC_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
