--------------------------------------------------------
--  DDL for Table QUESTION_ENTITY_QUE_OPTION
--------------------------------------------------------

  CREATE TABLE "GENIEQ"."QUESTION_ENTITY_QUE_OPTION" 
   (	"QUESTION_ENTITY_QUE_CODE" NUMBER(19,0) NOT NULL ENABLE, 
	"QUE_OPTION" CLOB, 
	 CONSTRAINT "FKHOVHF3U80MVLAFESAYPOGLYV8" FOREIGN KEY ("QUESTION_ENTITY_QUE_CODE")
	  REFERENCES "GENIEQ"."QUESTION" ("QUE_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("QUE_OPTION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
