--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "GENIEQ"."SUBJECT" ADD PRIMARY KEY ("SUB_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "GENIEQ"."SUBJECT" ADD CHECK (sub_type in ('인문','예술','사회','문화','과학','기술')) ENABLE
  ALTER TABLE "GENIEQ"."SUBJECT" MODIFY ("SUB_CODE" NOT NULL ENABLE)
