REM INSERTING into GENIEQ.TICKET
SET DEFINE OFF;
Insert into GENIEQ.TICKET (TIC_CODE,TIC_NUMBER,TIC_PRICE) values (1,10,10000);
Insert into GENIEQ.TICKET (TIC_CODE,TIC_NUMBER,TIC_PRICE) values (2,30,57000);
Insert into GENIEQ.TICKET (TIC_CODE,TIC_NUMBER,TIC_PRICE) values (3,50,90000);
commit;
