--------------------------------------------------------
--  파일이 생성됨 - 목요일-4월-10-2025   
--------------------------------------------------------
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\NOTICE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PASSAGE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PAYMENT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION_ENTITY_QUE_OPTION.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\SUBJECT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\TEST_MEMBER.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\TICKET.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\USAGE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\NOTICE_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PASSAGE_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PAYMENT_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION_ENTITY_QUE_OPTION_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\SUBJECT_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\TEST_MEMBER_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\TICKET_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\USAGE_DATA_TABLE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PK_NOTICE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PK_PASSAGE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PK_PAYMENT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PK_QUESTION.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\SYS_C007632.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\SYS_C007511.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\UK9EACS5V6VUSRIM2AN55BLU71G.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PK_TICKET.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PK_USAGE.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\NOTICE_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PASSAGE_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PAYMENT_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION_ENTITY_QUE_OPTION_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\SUBJECT_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\TEST_MEMBER_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\TICKET_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\USAGE_CONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PASSAGE_REFCONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\PAYMENT_REFCONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION_REFCONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\QUESTION_ENTITY_QUE_OPTION_REFCONSTRAINT.sql
@D:\EduTech_Full_Stack(D)\vue\GenieQ\backend\src\main\resources\initdata\USAGE_REFCONSTRAINT.sql
